Verschiedenes
Asklios/Bot4Future pull request #1
Opened 2021-04-24 17:47 UTC by DrDeee

Hallo @Asklios,
hier sind die ersten Teile meiner Verbesserungsvorschläge:
1. den InviteManager hab ich erstens auf Asyncronität umgeschrieben, d. h. da wird nichts mehr geblockt und der Bot sollte (unmerkbar) schneller sein 😄 . Außerdem hab ich den "kleinen" Fehler behoben, dass man mit dem Specialcode die Specialrole bekommt.
2. Der Profilbildgenerator hängt nun nichtmehr bei Profilbildern größer als 128px

Ich bin aber noch nicht fertig!
Lg DrDeee

2021-04-24 18:34 UTC, Asklios requested changes

2021-04-24 18:34 UTC, Asklios commented on Discord-Bot/src/main/java/InviteManager.java
> -                    Role role = this.roleDatabase.getSpecialRole(member.getGuild());
Wer über den specialCode beitritt soll die specialRole erhalten.

2021-04-26 09:41 UTC, DrDeee commented
- bump reminder hinzugefügt:
    - `bumprole @role` - setzen der Bumprole
    -  `getbumprole` - Anzeigen der Bumprole
    - Wenn jemand `!d bump` macht startet der Bot einen Scheduler, der nach zwei Stunden die Nachricht `@bumprole, ihr könnt wieder den Server bumpen!` sendet

2021-04-26 12:17 UTC, Asklios approved these changes

2021-04-26 12:17 UTC, Asklios commented on Discord-Bot/src/main/java/commands/server/bump/BumpRoleCommand.java
> +                channel.sendMessage("BumpRole wurde auf " + message.getMentionedRoles().get(0).getAsMention() + " gesetzt").queue(m -> m.delete().queueAfter(10,TimeUnit.SECONDS));
An manchen Stellen erwähnt der Bot Rollen bei commands. Um Shadow-Pings zu verhindern wäre es hier sinnvoll nur den Rollennamen und die ID als String anzugeben.
```suggestion
                channel.sendMessage("BumpRole wurde auf `" + message.getMentionedRoles().get(0).getName() + " (" + message.getMentionedRoles().get(0).getId() + ")` gesetzt.").queue(m -> m.delete().queueAfter(10,TimeUnit.SECONDS));
```

2021-04-26 12:17 UTC, Asklios commented on Discord-Bot/src/main/java/commands/server/bump/GetBumpRoleCommand.java
> +        channel.sendMessage("Die aktuelle verifiablerole ist " + bumpRole.getName() + " (" + bumpRole.getId() + ")")
Formatierung in Discord um die Rolle hervorzuheben.
```suggestion
        channel.sendMessage("Die aktuelle verifiablerole ist `" + bumpRole.getName() + " (" + bumpRole.getId() + ")`")
```

2021-04-27 07:55 UTC, merged